// Generated by LiveScript 1.2.0
(function(){
  var split$ = ''.split;
  $(function(){
    var score, key, record, items;
    score = 0;
    key = '';
    record = '';
    $('#proceed').hide();
    items = window.dodoData;
    $('#skip').click(function(){
      return refresh();
    });
    $('#next').click(function(){
      var row;
      score++;
      row = key + "," + $('.choice.green').attr('id') + "," + $('#reason').val().replace(/[\n,]/g, '，') + "\n";
      $.ajax({
        dataType: 'jsonp',
        url: "https://moedict.tw/dodo/log/?log=" + row
      });
      record += row;
      $('#progress-text').text(score + " / 5");
      $('#progress-bar').css('width', score / 5 * 100 + "%");
      if (score === 5) {
        alert('試玩結束！');
        alert(record);
        $('.choice').off('click');
        $('#next').fadeOut('fast');
        $('#skip').fadeOut('fast');
        return;
      }
      return refresh();
    });
    refresh();
    function refresh(){
      var ref$, book, xKey, x, yKey, y;
      ref$ = split$.call(items[Math.floor(Math.random() * items.length)], '\n'), book = ref$[0], xKey = ref$[1], x = ref$[2], yKey = ref$[3], y = ref$[4];
      key = xKey + "," + yKey;
      $('#book').text(book);
      $('#x').html(x.replace(/`/g, '<b>').replace(/~/g, '</b>'));
      $('#y').html(y.replace(/`/g, '<b>').replace(/~/g, '</b>'));
      $('.do-search').attr('target', '_blank');
      $('.do-search.x').attr('href', "https://www.google.com.tw/#q=\"" + x.replace(/[`~「」]/g, '') + "\"");
      $('.do-search.y').attr('href', "https://www.google.com.tw/#q=\"" + y.replace(/[`~「」]/g, '') + "\"");
      $('#reason').val('');
      $('#proceed').fadeOut('fast');
      $('.choice').removeClass('green');
      return $('.choice').click(function(){
        $('.choice').removeClass('green');
        $(this).addClass('green');
        return $('#proceed').fadeIn('fast', function(){
          return $('#reason').focus();
        });
      });
    }
    return refresh;
  });
}).call(this);
